module.exports = {
  SUCCEEDED: 'succeeded',
  FAILED: 'failed',
  DURATION: 2500,
  CHANGE_PASSWORD_SUCCEESS_MSG: 'Your password is updated successfully.',
  PROFILE_EDIT_SUCCEESS_MSG: 'Your profile is updated successfully.',
  CENTER_ADD_SUCCEESS_MSG: 'Your treatmnet center is added successfully.',
  CENTER_EDIT_SUCCEESS_MSG: 'Your treatmnet center is updated successfully.',
  CENTER_DELETE_SUCCEESS_MSG: 'Your treatment center is deleted successfully.',
  BANNER_EDIT_SUCCEESS_MSG: 'Banner updated successfully.',
  BANNER_ADD_SUCCEESS_MSG: 'Banner added successfully.',
  SPONSOR_EDIT_SUCCEESS_MSG: 'Sponsor updated successfully.',
  SPONSOR_ADD_SUCCEESS_MSG: 'Sponsor added successfully.',
  PAYMENT_EDIT_SUCCEESS_MSG: 'Payment Details updated successfully.',
  PAYMENT_ADD_SUCCEESS_MSG: 'Payment Details added successfully.',
  ADD_LISTING_SUCCEESS_MSG: 'Listing added successfully.',
  USER_ADD_SUCCESS_MSG: 'User added successfully.',
  PAYMENT_DELETE_SUCCEESS_MSG: 'Your Payment Details has been deleted successfully.',
  INQUIRY_SUCCESS_MSG: 'Your inquiry has been submitted successfully. We will contact soon.',
  SUBMIT_SUCCESS_MSG: 'Submitted successfully',
  FAILURE_MSG: 'Oops! Something is up. We are sorry for the inconvenience.',
  SIGNUP_CENTER: 'Treatment Center added successfully'
};
